/**
 * Stage the runtime next to the app.
 *
 * A packaged app ships the runtime beside itself, and the Rust bridge looks for
 * it at `runtime/tudouni-aigo[.exe]` (see `resolve_binary` in `src-tauri/src/
 * lib.rs`). During development that same path works: the debug executable lives
 * at `src-tauri/target/debug/`, and the bridge walks up three directories, so
 * `src-tauri/runtime/` is found.
 *
 * The layout has to match what `make release` stages, because the runtime decides
 * "am I in a package root?" by looking for a `prompts` directory, and a miss is
 * silent — the program starts and the `grep` tool simply disappears.
 *
 * These files are deliberately **not** committed: they are an 18 MB binary plus a
 * 4 MB ripgrep, both regenerated by `make release`, and committing them would let
 * them drift from `VERSION`. Run this after building a release.
 */

import { cpSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, statSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const appDir = resolve(here, '..');
const repoRoot = resolve(appDir, '..', '..');
const distDir = join(repoRoot, 'dist');
const destDir = join(appDir, 'src-tauri', 'runtime');

/** The only two platforms with a vendored ripgrep (`tools/vendor/rg/`). */
function hostTriple() {
  if (process.platform === 'win32' && process.arch === 'x64') return 'x86_64-pc-windows-msvc';
  if (process.platform === 'linux' && process.arch === 'x64') return 'x86_64-unknown-linux-musl';
  return null;
}

const triple = hostTriple();
if (!triple) {
  console.error(`unsupported host: ${process.platform}/${process.arch}`);
  console.error('the release targets are windows/amd64 and linux/amd64 only,');
  console.error('because tools/vendor/rg/ carries a ripgrep for those two and nothing else');
  process.exit(1);
}

const versionFile = join(repoRoot, 'VERSION');
const version = existsSync(versionFile) ? readFileSync(versionFile, 'utf8').trim() : '';

if (!existsSync(distDir)) {
  console.error(`no dist/ at ${distDir}`);
  console.error('build one first:  make release');
  process.exit(1);
}

// Prefer the directory matching the current VERSION; otherwise take any staging
// directory for this platform and say so, since a stale one is worse than none.
const candidates = readdirSync(distDir)
  .map((name) => join(distDir, name))
  .filter((path) => statSync(path).isDirectory() && path.endsWith(triple));

const exact = version ? candidates.find((path) => path.endsWith(`-${version}-${triple}`)) : null;
const source = exact ?? candidates[0] ?? null;

if (!source) {
  console.error(`no staged build for ${triple} under ${distDir}`);
  console.error('build one first:  make release');
  process.exit(1);
}

if (!exact) {
  console.warn(`warning: no build matching VERSION=${version || '(unreadable)'}; using ${source}`);
  console.warn('         --version in the app will not match the repository VERSION');
}

const binaryName = process.platform === 'win32' ? 'tudouni-aigo.exe' : 'tudouni-aigo';

/** Everything the runtime needs to be a package root, plus the vendored rg. */
const required = [
  binaryName,
  'prompts',
  'config.example.json',
  join('tools', 'vendor', 'rg', triple, process.platform === 'win32' ? 'rg.exe' : 'rg'),
];

for (const item of required) {
  if (!existsSync(join(source, item))) {
    console.error(`the staged build is missing ${item}`);
    console.error(`looked in ${source}`);
    process.exit(1);
  }
}

// Clear the previous staging, but keep the README that explains this directory.
for (const entry of readdirSync(destDir)) {
  if (entry === 'README.md') continue;
  rmSync(join(destDir, entry), { recursive: true, force: true });
}
mkdirSync(destDir, { recursive: true });

const copied = [];
for (const item of required) {
  cpSync(join(source, item), join(destDir, item), { recursive: true });
  copied.push(item);
}

console.log(`staged the runtime from ${source}`);
console.log('');
for (const item of copied) {
  const full = join(destDir, item);
  const size = statSync(full).isDirectory()
    ? `${readdirSync(full).length} file(s)`
    : `${(statSync(full).size / 1024 / 1024).toFixed(2)} MB`;
  console.log(`  ${item.padEnd(48)} ${size}`);
}
console.log('');
console.log('The bridge will find it at runtime/ next to the app.');
console.log('Now:  npm run tauri dev');
