/**
 * Contract tests: the front end's assumptions, checked against the runtime's own
 * bytes.
 *
 * Every other test in this suite checks the projection against a payload written
 * *by the front end*. That is exactly how the context bug survived a green
 * suite: `src/protocol/types.ts` declared the wrong shape, the fixture in
 * `projection.test.ts` was written to match that declaration, and the two agreed
 * with each other while disagreeing with the runtime.
 *
 * So these tests read `tests/fixtures/opening.jsonl` — captured from a real
 * binary by `scripts/capture-protocol.mjs` and frozen — and assert the front end
 * reads it correctly. The fixture is not regenerated by the test suite: it
 * carries one particular run's numbers, and a test that chased them would be
 * measuring the machine rather than the protocol.
 *
 * When the runtime changes, re-run the capture script and **review the diff by
 * hand**. A protocol change should show up here as a failing assertion rather
 * than as a blank screen in front of a user.
 */

import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { test } from 'node:test';

import { decodeLine } from '@/protocol/types';
import { registerRuntime } from '@/runtime/bus';
import { activeRuntime, createSessionBucket, useApp, type SessionRuntime } from '@/state/store';
import type { Entry } from '@/state/entries';

// Resolved from the project root, not from `import.meta.url`: the tests are
// bundled into `.test-build/` before they run, so a path relative to this module
// would point inside the build directory. The runner sets `cwd` to the root.
const fixturePath = resolve(process.cwd(), 'tests', 'fixtures', 'opening.jsonl');

/** The frozen capture: one JSON message per line, in the order it was sent. */
function readFixture(): unknown[] {
  const text = readFileSync(fixturePath, 'utf8');
  return text
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line !== '')
    .map((line) => JSON.parse(line));
}

/**
 * The key the fake child is registered under.
 *
 * Every fact in this build is per session now, so a test needs a session before
 * it can assert anything about one. A fresh bucket is exactly what
 * `attachSession` installs once the bridge accepts a child, so building one here
 * exercises the same shapes the real path produces.
 */
const KEY = 'k-1';

/** Put the store back to its pre-handshake state, with one session installed. */
function reset(): void {
  useApp.setState({
    sessions: {
      [KEY]: createSessionBucket(KEY, 'C:/work', { ericai: false, maxSteps: null }),
    },
    order: [KEY],
    activeKey: KEY,
    modal: null,
    pendingModals: [],
    panel: null,
    startupProblem: null,
  });
}

/** Feed every line of the capture through the decoder and the store, exactly as
 *  the real bridge does — tagged with the session the line came from, because
 *  that tag is the only thing that says whose line it is. */
function replay(key = KEY): void {
  for (const raw of readFixture()) {
    const decoded = decodeLine(JSON.stringify(raw));
    assert.notEqual(decoded.msg, null, 'every captured line must decode');
    assert.equal(decoded.fatal, undefined);
    useApp.getState().applyRuntimeMessage(key, decoded.msg as never);
  }
}

/**
 * The session being shown, with the assertion that it exists folded in.
 *
 * Every fact this build stores is per session, so a test that read
 * `rt().context` before now reads `rt().context` — the difference
 * being that this makes the session part of the assertion rather than implicit.
 */
function rt(): SessionRuntime {
  const bucket = activeRuntime(useApp.getState());
  assert.ok(bucket, 'a session must be installed');
  return bucket;
}

test('the frozen capture still decodes line for line', () => {
  reset();
  const raw = readFixture();
  // The capture drives `context` and `tools` on top of the opening, so it is
  // five lines. Asserting the count keeps a truncated fixture from silently
  // weakening every test below it.
  assert.equal(raw.length, 5, 'the fixture is init/session_load/ui(state)/ui(context)/ui(tools)');

  const kinds = raw.map((msg) => {
    const m = msg as { t: string; kind?: string };
    return m.kind ? `${m.t}/${m.kind}` : m.t;
  });
  assert.deepEqual(kinds, [
    'init',
    'session_load',
    'ui/state',
    'ui/context',
    'ui/tools',
  ]);
});

test('the context ledger is nested, and every number survives the projection', () => {
  reset();
  replay();

  const context = rt().context;
  assert.ok(context, 'ui(context) must have produced a context');

  // These four come from the *inner* object. Reading the outer one — the old
  // bug — produced `used: unknown` and no percentage at all.
  assert.equal(context.used, 3791);
  assert.equal(context.limitTokens, 896313);
  assert.equal(context.window, 1000000);
  assert.equal(context.percent, 3791 / 1000000);

  // The outer object carries these, and they are not part of the ledger.
  assert.equal(context.messages, 1);
  assert.equal(context.active, false);
  assert.equal(context.folded, 0);

  // `present` means "there is a ledger here", which is why it reads the inner
  // object: an empty outer one is how the runtime says there is no context
  // management, and a row of zeroes would be a different and false statement.
  assert.equal(context.present, true);
});

test('`degraded` is a count on the wire, not a flag', () => {
  reset();
  replay();

  const context = rt().context;
  assert.ok(context);
  // The runtime sends `len(LastDegraded)` — a number. Declaring it `boolean` and
  // testing `typeof === 'boolean'` made it permanently null.
  assert.equal(typeof context.degraded, 'number');
  assert.equal(context.degraded, 0);
});

test('the handshake notices are still on screen after session_load', () => {
  reset();

  const raw = readFixture();
  const init = raw[0] as { notices: unknown[] };
  assert.ok(init.notices.length > 0, 'the capture must carry notices to test this');

  replay();

  const bucket = rt();
  // `init` is followed immediately and unconditionally by `session_load`, which
  // rebuilds the stream. Keeping the notices in `entries` alone meant they were
  // wiped before the first frame was drawn.
  assert.equal(bucket.handshakeNotices.length, init.notices.length);
  const inStream = bucket.entries.filter((entry) => entry.kind === 'note');
  assert.equal(inStream.length, init.notices.length);
  assert.equal(
    (inStream[0] as Extract<Entry, { kind: 'note' }>).text,
    (init.notices[0] as { text: string }).text,
  );
});

test('the tool registry arrives with the handshake, not only with ui(tools)', () => {
  reset();

  const init = readFixture()[0] as { tools: Array<{ name: string; risk: string }> };
  assert.ok(init.tools.length > 0);

  replay();

  // A `tool_call` event carries no risk of its own, so without the handshake's
  // registry every tool row's badge is permanently unknown — `ui(tools)` only
  // ever arrives because somebody opened the `/tools` screen.
  // Per session: the registry is that child's tool set, and `toolFacts` reads
  // the active one.
  const facts = useApp.getState().toolFacts('shell');
  assert.ok(facts, 'shell must be known');
  assert.equal(facts.risk, 'high');
  assert.equal(facts.parallelSafe, false);
});

test('the session list is asked for, so the first screen can fill its slots', () => {
  // The first screen shows the four most recent sessions; before this, nothing
  // ever requested them and `Ctrl+1..9` had nothing to switch to.
  //
  // The message goes to **this session's** runtime, which is what the fake
  // handle stands in for: with one process per conversation, "who was asked" is
  // as much a part of the assertion as "was anything asked".
  const sent: string[] = [];
  registerRuntime({
    key: KEY,
    send(msg) {
      sent.push(msg.t);
    },
    subscribe() {
      return () => undefined;
    },
    dispose() {
      return undefined;
    },
  });

  reset();
  replay();

  assert.ok(sent.includes('session_list'), 'init must ask for the session list');
});
